language: node_js
node_js: '10'
after_success:
  yarn build
deploy:
  on:
    branch: master
  provider: s3
  region: us-east-1
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET
  acl: public_read
  local_dir: dist
  skip_cleanup: true
  